-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-11-23 21:00:35 MUT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



ALTER TABLE DW_FACT_WDIDATA 
    DROP CONSTRAINT DW_FACT_WDIDATA_DW_DIM_COUNTRY_FK 
GO

DROP TABLE DW_DIM_COUNTRY
GO

ALTER TABLE DW_FACT_WDIDATA 
    DROP CONSTRAINT DW_FACT_WDIDATA_DW_DIM_TIME_FK 
GO

DROP TABLE DW_DIM_TIME
GO

DROP TABLE DW_FACT_WDIDATA
GO

DROP TABLE REF_KPILIST
GO

DROP TABLE REF_LogScripts
GO

DROP TABLE REF_PARAMETERS
GO

DROP TABLE REF_REPORTING_COUNTRY
GO

DROP TABLE STG_CPIDATA
GO

DROP TABLE STG_WDICOUNTRY
GO

DROP TABLE STG_WDIDATA
GO

DROP TABLE STG_YEARS
GO

CREATE TABLE DW_DIM_COUNTRY 
    (
     CountryID BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     CountryCode VARCHAR (20) , 
     ShortName VARCHAR (50) , 
     TableName VARCHAR (50) , 
     LongName VARCHAR (255) , 
     Region VARCHAR (50) 
    )
GO

ALTER TABLE DW_DIM_COUNTRY ADD CONSTRAINT DW_DIM_COUNTRY_PK PRIMARY KEY CLUSTERED (CountryID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DW_DIM_TIME 
    (
     TimeID BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     Year NUMERIC (10) , 
     StartDate DATE 
    )
GO

ALTER TABLE DW_DIM_TIME ADD CONSTRAINT DW_DIM_TIME_PK PRIMARY KEY CLUSTERED (TimeID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DW_FACT_WDIDATA 
    (
     WDIDataID BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     CountryID BIGINT NOT NULL , 
     TimeID BIGINT NOT NULL , 
     CountryName VARCHAR (100) , 
     CountryCode VARCHAR (20) , 
     Year NUMERIC (10) , 
     ER_FSH_PROD_MT NUMERIC (20,4) , 
     AG_LND_AGRI_K2 NUMERIC (20,4) , 
     IC_REG_DURS NUMERIC (20,4) , 
     IC_BUS_NREG NUMERIC (20,4) , 
     SL_AGR_EMPL_ZS NUMERIC (20,4) , 
     SL_EMP_SELF_ZS NUMERIC (20,4) , 
     CPI NUMERIC (20,4) 
    )
GO

ALTER TABLE DW_FACT_WDIDATA ADD CONSTRAINT DW_FACT_WDIDATA_PK PRIMARY KEY CLUSTERED (WDIDataID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REF_KPILIST 
    (
     KPINUMBER NUMERIC (10) , 
     KPICODE VARCHAR (30) , 
     KPIDESCRIPTION VARCHAR (255) , 
     DBCOLUMNNAME VARCHAR (30) , 
     FORMULA VARCHAR (MAX) 
    )
GO

CREATE TABLE REF_LogScripts 
    (
     LogID BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     DateLog DATETIME , 
     Description VARCHAR (255) , 
     SQLScript VARCHAR (MAX) 
    )
GO

ALTER TABLE REF_LogScripts ADD CONSTRAINT REF_LogScripts_PK PRIMARY KEY CLUSTERED (LogID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REF_PARAMETERS 
    (
     YearStartLoad NUMERIC (10) 
    )
GO

CREATE TABLE REF_REPORTING_COUNTRY 
    (
     CountryCode VARCHAR (20) 
    )
GO

CREATE TABLE STG_CPIDATA 
    (
     Country VARCHAR (50) , 
     ISO3CountryCode VARCHAR (10) , 
     Region VARCHAR (20) , 
     CPIScore VARCHAR (20) , 
     Rank VARCHAR (20) , 
     Sources VARCHAR (20) , 
     StandardError VARCHAR (20) , 
     Year VARCHAR (10) 
    )
GO

CREATE TABLE STG_WDICOUNTRY 
    (
     CountryCode VARCHAR (20) , 
     ShortName VARCHAR (50) , 
     TableName VARCHAR (50) , 
     LongName VARCHAR (100) , 
     TwoAlphaCode VARCHAR (10) , 
     CurrencyUnit VARCHAR (50) , 
     SpecialNotes VARCHAR (4000) , 
     Region VARCHAR (50) , 
     IncomeGroup VARCHAR (255) , 
     WB2code VARCHAR (255) , 
     NationalAccountsBaseYear VARCHAR (255) , 
     NationalAccountsReferenceYear VARCHAR (255) , 
     SNAPriceValuation VARCHAR (4000) , 
     LendingCategory VARCHAR (255) , 
     OtherGroups VARCHAR (255) , 
     SystemofNationalAccounts VARCHAR (4000) , 
     AlternativeConversionFactor VARCHAR (255) , 
     PPPSurveyYear VARCHAR (255) , 
     BalanceofPaymentsManualinUse VARCHAR (255) , 
     ExternalDebtReportingStatus VARCHAR (255) , 
     SystemOfTrade VARCHAR (255) , 
     GovernmentAccountingconcept VARCHAR (255) , 
     IMFDataDisseminationStandard VARCHAR (255) , 
     LatestPopulationCensus VARCHAR (255) , 
     LatestHouseholdSurvey VARCHAR (255) , 
     SourceOfMostRecentIncExp VARCHAR (255) , 
     VitalRegistrationComplete VARCHAR (255) , 
     LatestAgriculturalCensus VARCHAR (255) , 
     LatestIndustrialData VARCHAR (255) , 
     LatestTradeData VARCHAR (4000) 
    )
GO

CREATE TABLE STG_WDIDATA 
    (
     CountryName VARCHAR (100) , 
     CountryCode VARCHAR (20) , 
     IndicatorName VARCHAR (255) , 
     IndicatorCode VARCHAR (50) , 
     YR1960 VARCHAR (50) , 
     YR1961 VARCHAR (50) , 
     YR1962 VARCHAR (50) , 
     YR1963 VARCHAR (50) , 
     YR1964 VARCHAR (50) , 
     YR1965 VARCHAR (50) , 
     YR1966 VARCHAR (50) , 
     YR1967 VARCHAR (50) , 
     YR1968 VARCHAR (50) , 
     YR1969 VARCHAR (50) , 
     YR1970 VARCHAR (50) , 
     YR1971 VARCHAR (50) , 
     YR1972 VARCHAR (50) , 
     YR1973 VARCHAR (50) , 
     YR1974 VARCHAR (50) , 
     YR1975 VARCHAR (50) , 
     YR1976 VARCHAR (50) , 
     YR1977 VARCHAR (50) , 
     YR1978 VARCHAR (50) , 
     YR1979 VARCHAR (50) , 
     YR1980 VARCHAR (50) , 
     YR1981 VARCHAR (50) , 
     YR1982 VARCHAR (50) , 
     YR1983 VARCHAR (50) , 
     YR1984 VARCHAR (50) , 
     YR1985 VARCHAR (50) , 
     YR1986 VARCHAR (50) , 
     YR1987 VARCHAR (50) , 
     YR1988 VARCHAR (50) , 
     YR1989 VARCHAR (50) , 
     YR1990 VARCHAR (50) , 
     YR1991 VARCHAR (50) , 
     YR1992 VARCHAR (50) , 
     YR1993 VARCHAR (50) , 
     YR1994 VARCHAR (50) , 
     YR1995 VARCHAR (50) , 
     YR1996 VARCHAR (50) , 
     YR1997 VARCHAR (50) , 
     YR1998 VARCHAR (50) , 
     YR1999 VARCHAR (50) , 
     YR2000 VARCHAR (50) , 
     YR2001 VARCHAR (50) , 
     YR2002 VARCHAR (50) , 
     YR2003 VARCHAR (50) , 
     YR2004 VARCHAR (50) , 
     YR2005 VARCHAR (50) , 
     YR2006 VARCHAR (50) , 
     YR2007 VARCHAR (50) , 
     YR2008 VARCHAR (50) , 
     YR2009 VARCHAR (50) , 
     YR2010 VARCHAR (50) , 
     YR2011 VARCHAR (50) , 
     YR2012 VARCHAR (50) , 
     YR2013 VARCHAR (50) , 
     YR2014 VARCHAR (50) , 
     YR2015 VARCHAR (50) , 
     YR2016 VARCHAR (50) , 
     YR2017 VARCHAR (50) , 
     YR2018 VARCHAR (50) , 
     YR2019 VARCHAR (50) , 
     YR2020 VARCHAR (50) 
    )
GO

CREATE TABLE STG_YEARS 
    (
     Year VARCHAR (10) , 
     StartDate VARCHAR (20) 
    )
GO

ALTER TABLE DW_FACT_WDIDATA 
    ADD CONSTRAINT DW_FACT_WDIDATA_DW_DIM_COUNTRY_FK FOREIGN KEY 
    ( 
     CountryID
    ) 
    REFERENCES DW_DIM_COUNTRY 
    ( 
     CountryID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DW_FACT_WDIDATA 
    ADD CONSTRAINT DW_FACT_WDIDATA_DW_DIM_TIME_FK FOREIGN KEY 
    ( 
     TimeID
    ) 
    REFERENCES DW_DIM_TIME 
    ( 
     TimeID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
